from django.db import models

# Create your models here.


class Track(models.Model):
    # id is auto generated by django, and that's going be used as the primary key for each of the tracks
    title = models.CharField(verbose_name="track", max_length=50)
    description = models.TextField(verbose_name="description", blank=True)
    url = models.URLField()
    created_at = models.DateTimeField(auto_now_add=True)
